name: Strapi_Fargate

on:
  push:
    branches: developer # I dont want to trigger piepline to I change it into deploy

jobs:
  docker-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: v${{ github.run_number }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/strapi3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: |
        docker build \
        --build-arg HOST=0.0.0.0 \
        --build-arg PORT=1337 \
        --build-arg APP_KEYS=${{secrets.APP_KEYS}} \
        --build-arg API_TOKEN_SALT=${{secrets.API_TOKEN_SALT}} \
        --build-arg ADMIN_JWT_SECRET=${{secrets.ADMIN_JWT_SECRET}} \
        --build-arg TRANSFER_TOKEN_SALT=${{secrets.TRANSFER_TOKEN_SALT}} \
        --build-arg JWT_SECRET=${{secrets.JWT_SECRET}} \
        --build-arg ENCRYPTION_KEY=${{secrets.ENCRYPTION_KEY}} \
        -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} ./strapi_task7/

    - name: Push the image
      run: |
        docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
        
    - name: terraform setup
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Import terrfrom.tfstate file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: location of terraform file
        path: ./terraform/terraform.tfstate